language: php
php:
  - '8.1'
  - '8.2'
  - '8.3'
  - '8.4'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer dump-autoload

script:
  - vendor/bin/phpunit
