language: php
php:
  - '7.4'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer dump-autoload

script:
  - vendor/bin/phpunit
